export enum RABBITMQ_NAME {
  SCHEDULING_SERVICE = 'SCHEDULING_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
}

export enum RABBITMQ_QUEUE {
  SCHEDULER_CONSUMER = 'SCHEDULER_CONSUMER',
  SCHEDULER_PRODUCER = 'SCHEDULER',
  USER = 'USER',
  NOTIFICATION = 'NOTIFICATION',
}

export enum RABBITMQ_LABEL {
  SCHEDULE_TASK = 'SCHEDULE_TASK',
  SEND_WELCOME_PUSH_NOTIFICATION = 'SEND_WELCOME_PUSH_NOTIFICATION',
  USER_CREATED = 'USER_CREATED',
  SEND_PUSH_NOTIFICATION = 'SEND_PUSH_NOTIFICATION',
}
