export enum RABBITMQ_NAME {
  SCHEDULING_SERVICE = 'SCHEDULING_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
}

export enum RABBITMQ_QUEUE {
  SCHEDULER_CONSUMER = 'SCHEDULER_CONSUMER',
  SCHEDULER_PRODUCER = 'SCHEDULER',
  USER = 'USER',
}

export enum RABBITMQ_LABEL {
  SCHEDULE_TASK = 'SCHEDULE_TASK',
}
